#!/usr/bin/env python3

# ------------------------------------------------------------------------

def setUp():
  print(""); print("***************************************"); print("")
  
  print("Did we make a github program that can be run somewhere?")
  
  print("This was typed in test branch @1:10 pm-ish")

  print("what the fuck from command line")  

  print("added from new folder for testing 20170808ish")
  print("Random change from jonnyProgrammer side.")
  
  print(""); print("***************************************"); print("")
  
# ------------------------------------------------------------------------

def main():

  setUp()
  
# ------------------------------------------------------------------------
main()
# ------------------------------------------------------------------------
